# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_created'], 'verbose_name': 'Blog Entry', 'verbose_name_plural': 'Blog Entries'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='modified',
            new_name='date_modified',
        ),
        migrations.AddField(
            model_name='entry',
            name='body_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
